import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import AuthProvider from "@/contexts/AuthContext";
import DashboardSidebar from "@/components/dashboard-sidebar";
import { Toaster } from "sonner";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${inter.variable} antialiased flex flex-row min-h-screen`}
      >
        <AuthProvider>
          <DashboardSidebar />
          <Toaster />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
